all collect all, cache and write with cat

diff --git a/.github/workflows/build-test.yml b/.github/workflows/build-test.yml
--- a/.github/workflows/build-test.yml
+++ b/.github/workflows/build-test.yml
@@ -99,14 +99,28 @@ jobs:
         run: echo "BAZEL_TESTLOGS_PATH=$(bazel info bazel-testlogs)" >> $GITHUB_ENV
 
 
-      - name: Collect all MD5 coverage.dat files
+      # - name: Collect all MD5 coverage.dat files
+      #   run: |
+      #     mkdir -p coverage-artifacts
+      #     find ${{ env.BAZEL_TESTLOGS_PATH }} -type f -name "coverage.dat" -print0 | \
+      #     while IFS= read -r -d '' file; do
+      #       # md5sum "$file"
+      #       head -n 5 "$file" 
+      #     done
+
+      - name: Test write access (without cp)
         run: |
-          mkdir -p coverage-artifacts
+          mkdir -p coverage-artifacts/test-write
+          echo "Testing write access..."
           find ${{ env.BAZEL_TESTLOGS_PATH }} -type f -name "coverage.dat" -print0 | \
           while IFS= read -r -d '' file; do
-            # md5sum "$file"
-            head -n 5 "$file" 
+            base=$(basename "$file")
+            echo "Writing test copy for $file"
+            cat "$file" > "coverage-artifacts/test-write/$base" || echo "⚠️ Could not write $base"
           done
+          echo "Listing written files:"
+          ls -lh coverage-artifacts/test-write || true
+
 
       # - name: Collect all coverage.dat files
       #   run: |
