ACTIVE 1: Uncomment test and delete empty functions

diff --git a/.github/workflows/build-test.yml b/.github/workflows/build-test.yml
--- a/.github/workflows/build-test.yml
+++ b/.github/workflows/build-test.yml
@@ -150,19 +150,19 @@ jobs:
 
 
 
-#      - name: Run tests with coverage
-#        id: run-coverage
-#        env:
-#          COVERAGE_EXCLUSIONS: ${{ steps.compute-coverage-exclusions.outputs.exclusion_filter }}
-#          USE_CACHE: ${{ inputs.disable-cache-for-coverage && 'no' || 'yes' }}
-#        run: >
-#          bazel coverage
-#          --cache_test_results=yes
-#          --experimental_split_coverage_postprocessing
-#          --experimental_fetch_all_coverage_outputs
-#          --instrumentation_filter="//src/main/kotlin/.*,//src/main/python/.*,//src/main/cc/.*,-@.*,-src/main/.*/testing.*,-src/main/.*/loadtest.*,${COVERAGE_EXCLUSIONS}"
-#          //src/test/kotlin/org/wfanet/measurement/integration/deploy/gcloud:GCloudSpannerInProcessReachMeasurementAccuracyTest
-#        continue-on-error: true
+      - name: Run tests with coverage
+        id: run-coverage
+        env:
+          COVERAGE_EXCLUSIONS: ${{ steps.compute-coverage-exclusions.outputs.exclusion_filter }}
+          USE_CACHE: ${{ inputs.disable-cache-for-coverage && 'no' || 'yes' }}
+        run: >
+          bazel coverage
+          --cache_test_results=yes
+          --experimental_split_coverage_postprocessing
+          --experimental_fetch_all_coverage_outputs
+          --instrumentation_filter="//src/main/kotlin/.*,//src/main/python/.*,//src/main/cc/.*,-@.*,-src/main/.*/testing.*,-src/main/.*/loadtest.*,${COVERAGE_EXCLUSIONS}"
+          //src/test/kotlin/org/wfanet/measurement/integration/deploy/gcloud:GCloudInProcessModelRepositoryCliIntegrationTest
+        continue-on-error: true
 #//src/test/kotlin/org/wfanet/measurement/integration/deploy/gcloud/...
 #-//src/test/kotlin/org/wfanet/measurement/integration/deploy/gcloud:GCloudSpannerInProcessMeasurementSystemProberIntegrationTest NV
 #-//src/test/kotlin/org/wfanet/measurement/integration/deploy/gcloud:GCloudInProcessReportingEventGroupsTest NV
@@ -222,31 +222,31 @@ jobs:
       #  GCloudInProcessAccessCliIntegrationTest
       #  GCloudInProcessReportingEventGroupsTest
 
-
-      - name: Run tests with coverage
-        id: run-coverage
-        env:
-          COVERAGE_EXCLUSIONS: ${{ steps.compute-coverage-exclusions.outputs.exclusion_filter }}
-          USE_CACHE: ${{ inputs.disable-cache-for-coverage && 'no' || 'yes' }}
-        run: |
-          set -o pipefail
-          bazel coverage \
-            --cache_test_results=yes \
-            --experimental_split_coverage_postprocessing \
-            --experimental_fetch_all_coverage_outputs \
-            --test_output=all \
-            --runs_per_test=10 \
-            --instrumentation_filter="//src/main/kotlin/.*,//src/main/python/.*,//src/main/cc/.*,-@.*,-src/main/.*/testing.*,-src/main/.*/loadtest.*,${COVERAGE_EXCLUSIONS}" \
-            //src/test/kotlin/org/wfanet/measurement/integration/deploy/gcloud:GCloudInProcessModelRepositoryCliIntegrationTest \
-            | tee /tmp/coverage_runs.log
-        continue-on-error: true
-
-
-      - name: Find nondeterminism signals
-        if: always()
-        run: |
-          echo "=== matches ==="
-          grep -E "advanceComputation attempt|Failure happened during setContinuationToken|version mismatch" /tmp/coverage_runs.log || true
+#
+#      - name: Run tests with coverage
+#        id: run-coverage
+#        env:
+#          COVERAGE_EXCLUSIONS: ${{ steps.compute-coverage-exclusions.outputs.exclusion_filter }}
+#          USE_CACHE: ${{ inputs.disable-cache-for-coverage && 'no' || 'yes' }}
+#        run: |
+#          set -o pipefail
+#          bazel coverage \
+#            --cache_test_results=yes \
+#            --experimental_split_coverage_postprocessing \
+#            --experimental_fetch_all_coverage_outputs \
+#            --test_output=all \
+#            --runs_per_test=10 \
+#            --instrumentation_filter="//src/main/kotlin/.*,//src/main/python/.*,//src/main/cc/.*,-@.*,-src/main/.*/testing.*,-src/main/.*/loadtest.*,${COVERAGE_EXCLUSIONS}" \
+#            //src/test/kotlin/org/wfanet/measurement/integration/deploy/gcloud:GCloudInProcessModelRepositoryCliIntegrationTest \
+#            | tee /tmp/coverage_runs.log
+#        continue-on-error: true
+#
+#
+#      - name: Find nondeterminism signals
+#        if: always()
+#        run: |
+#          echo "=== matches ==="
+#          grep -E "advanceComputation attempt|Failure happened during setContinuationToken|version mismatch" /tmp/coverage_runs.log || true
 
 
       - name: Bazel output path
